/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SSlugIndexRouteImport } from './routes/s/$slug/index'
import { Route as AuthenticatedExploreIndexRouteImport } from './routes/_authenticated/explore/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedNotesNewIndexRouteImport } from './routes/_authenticated/notes/new/index'
import { Route as AuthenticatedNotesIdIndexRouteImport } from './routes/_authenticated/notes/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExploreIndexRoute =
  AuthenticatedExploreIndexRouteImport.update({
    id: '/explore/',
    path: '/explore/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotesNewIndexRoute =
  AuthenticatedNotesNewIndexRouteImport.update({
    id: '/notes/new/',
    path: '/notes/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesIdIndexRoute =
  AuthenticatedNotesIdIndexRouteImport.update({
    id: '/notes/$id/',
    path: '/notes/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/explore/': typeof AuthenticatedExploreIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/notes/$id/': typeof AuthenticatedNotesIdIndexRoute
  '/notes/new/': typeof AuthenticatedNotesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/explore': typeof AuthenticatedExploreIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/notes/$id': typeof AuthenticatedNotesIdIndexRoute
  '/notes/new': typeof AuthenticatedNotesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/explore/': typeof AuthenticatedExploreIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/_authenticated/notes/$id/': typeof AuthenticatedNotesIdIndexRoute
  '/_authenticated/notes/new/': typeof AuthenticatedNotesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/api/auth/$'
    | '/explore/'
    | '/s/$slug/'
    | '/notes/$id/'
    | '/notes/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/explore'
    | '/s/$slug'
    | '/notes/$id'
    | '/notes/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/login/'
    | '/api/auth/$'
    | '/_authenticated/explore/'
    | '/s/$slug/'
    | '/_authenticated/notes/$id/'
    | '/_authenticated/notes/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/explore/': {
      id: '/_authenticated/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof AuthenticatedExploreIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notes/new/': {
      id: '/_authenticated/notes/new/'
      path: '/notes/new'
      fullPath: '/notes/new/'
      preLoaderRoute: typeof AuthenticatedNotesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/$id/': {
      id: '/_authenticated/notes/$id/'
      path: '/notes/$id'
      fullPath: '/notes/$id/'
      preLoaderRoute: typeof AuthenticatedNotesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExploreIndexRoute: typeof AuthenticatedExploreIndexRoute
  AuthenticatedNotesIdIndexRoute: typeof AuthenticatedNotesIdIndexRoute
  AuthenticatedNotesNewIndexRoute: typeof AuthenticatedNotesNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExploreIndexRoute: AuthenticatedExploreIndexRoute,
  AuthenticatedNotesIdIndexRoute: AuthenticatedNotesIdIndexRoute,
  AuthenticatedNotesNewIndexRoute: AuthenticatedNotesNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SSlugIndexRoute: SSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
